--------------------------------------------------------
-- Archivo creado  - sábado-junio-30-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USUARIOCONVENIO
--------------------------------------------------------

  CREATE TABLE "MUNICIPALIDAD"."USUARIOCONVENIO" 
   (	"ID_USUARIOCONVENIO" NUMBER(*,0), 
	"RUT" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into MUNICIPALIDAD.USUARIOCONVENIO
SET DEFINE OFF;
Insert into MUNICIPALIDAD.USUARIOCONVENIO (ID_USUARIOCONVENIO,RUT,NOMBRE,APELLIDO) values ('1','17680854-3','Javier','Gonzlez');
Insert into MUNICIPALIDAD.USUARIOCONVENIO (ID_USUARIOCONVENIO,RUT,NOMBRE,APELLIDO) values ('2','19319652-7','Erick','Aguila');
Insert into MUNICIPALIDAD.USUARIOCONVENIO (ID_USUARIOCONVENIO,RUT,NOMBRE,APELLIDO) values ('3','17928675-0 ','Patricio ','Alfaro');
Insert into MUNICIPALIDAD.USUARIOCONVENIO (ID_USUARIOCONVENIO,RUT,NOMBRE,APELLIDO) values ('4','13965092-1 ','Gonzalo','Perez');
Insert into MUNICIPALIDAD.USUARIOCONVENIO (ID_USUARIOCONVENIO,RUT,NOMBRE,APELLIDO) values ('5','16647779-4 ','Eduardo','Perez');
Insert into MUNICIPALIDAD.USUARIOCONVENIO (ID_USUARIOCONVENIO,RUT,NOMBRE,APELLIDO) values ('6','18906069-6 ','Javiera','Perez');
Insert into MUNICIPALIDAD.USUARIOCONVENIO (ID_USUARIOCONVENIO,RUT,NOMBRE,APELLIDO) values ('7','19190671-3 ','Jose','Perez');
Insert into MUNICIPALIDAD.USUARIOCONVENIO (ID_USUARIOCONVENIO,RUT,NOMBRE,APELLIDO) values ('8','17270527-8 ','Maria','Perez');
Insert into MUNICIPALIDAD.USUARIOCONVENIO (ID_USUARIOCONVENIO,RUT,NOMBRE,APELLIDO) values ('9','18546252-8 ','Bernardo','Perez');
Insert into MUNICIPALIDAD.USUARIOCONVENIO (ID_USUARIOCONVENIO,RUT,NOMBRE,APELLIDO) values ('10','9155283-3 ','Roberto','Perez');
Insert into MUNICIPALIDAD.USUARIOCONVENIO (ID_USUARIOCONVENIO,RUT,NOMBRE,APELLIDO) values ('11','19340717-K ','Imael','Perez');
Insert into MUNICIPALIDAD.USUARIOCONVENIO (ID_USUARIOCONVENIO,RUT,NOMBRE,APELLIDO) values ('12','19572663-9 ','Miguel','Perez');
Insert into MUNICIPALIDAD.USUARIOCONVENIO (ID_USUARIOCONVENIO,RUT,NOMBRE,APELLIDO) values ('13','18882760-8 ','Nicole','Perez');
Insert into MUNICIPALIDAD.USUARIOCONVENIO (ID_USUARIOCONVENIO,RUT,NOMBRE,APELLIDO) values ('14','18597066-3 ','Lucas','Perez');
--------------------------------------------------------
--  DDL for Index USUARIOCONVENIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MUNICIPALIDAD"."USUARIOCONVENIO_PK" ON "MUNICIPALIDAD"."USUARIOCONVENIO" ("ID_USUARIOCONVENIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Package USUARIO_CONVENIO
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "MUNICIPALIDAD"."USUARIO_CONVENIO" AS 
procedure proc_obtener_usuarioconvenio(rut_usuario varchar2,pcursor out sys_refcursor);
  /* TODO enter package declarations (types, exceptions, methods etc) here */ 

END Usuario_Convenio;


/
--------------------------------------------------------
--  DDL for Package Body USUARIO_CONVENIO
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "MUNICIPALIDAD"."USUARIO_CONVENIO" AS

  procedure proc_obtener_usuarioconvenio(rut_usuario varchar2,pcursor out sys_refcursor) AS
  BEGIN
    OPEN pcursor FOR
    SELECT RUT,NOMBRE,APELLIDO FROM USUARIOCONVENIO 
    where RUT=rut_usuario;
  END proc_obtener_usuarioconvenio;

END USUARIO_CONVENIO;


/
--------------------------------------------------------
--  Constraints for Table USUARIOCONVENIO
--------------------------------------------------------

  ALTER TABLE "MUNICIPALIDAD"."USUARIOCONVENIO" MODIFY ("ID_USUARIOCONVENIO" NOT NULL ENABLE);
  ALTER TABLE "MUNICIPALIDAD"."USUARIOCONVENIO" MODIFY ("RUT" NOT NULL ENABLE);
  ALTER TABLE "MUNICIPALIDAD"."USUARIOCONVENIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "MUNICIPALIDAD"."USUARIOCONVENIO" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "MUNICIPALIDAD"."USUARIOCONVENIO" ADD CONSTRAINT "USUARIOCONVENIO_PK" PRIMARY KEY ("ID_USUARIOCONVENIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
